### ISSUE TITLE
Select specific fields through LinqRepository fluent api

### ISSUE THREAD

**Issue by bugMaker-237** [IRCraziestTaxi/typeorm-linq-repository#102]
Hello, very nice library. Coming from a .net background, it's easy to implement my repo pattern with this.

Actually i'm not able to select specific fields using the LinqRepository fluent api. So i tried to get the underlying queryBuilder to append to it the select action with specific fields. But IQuery is not exposing the property.

```TS
const queryBuilder: QueryBuilder<T> = (query as any).query;
queryBuilder.select(spec.selector.fields || []);
```
This is what i suppose i could do to get the queryBuilder. Setting this back is even uglier

```TS
(query as any)._query = queryBuilder;
```
Is there a way to select specific fields using linqRepository fluent api ? or can we expose query property or encapsulate the query poperty with some kind of methods that will check the query before setting ?

**Comment by IRCraziestTaxi** [comment]
Hey @bugMaker-237, sorry, just now getting around to really looking at this.

This repository's Query class does have a `select` method, but right now its only purpose is to select a property for "inner queries" (`IN (...)` and `NOT IN (...)` queries). I gave it a quick look and I believe the `select` method could be modified to behave like TypeORM's `select` method, but in the spirit of maintaining the type safety this library was built for, I would expect arguments to be lambdas, i.e. `select(x => x.prop, x => x.prop, ...)`.

Can you tell me more about your use case and what the contents of `spec.selector.fields` are?

**Comment by IRCraziestTaxi** [comment]
@bugMaker-237 I'm going through old issues and looking to close what I can. I'm going to go ahead and close this one for now, but feel free to reopen it if you can tell me more about your use case and what the contents of `spec.selector.fields` are.
