### ISSUE TITLE
Equivalent of inner join

### ISSUE THREAD

**Issue by 19majkel94** [IRCraziestTaxi/typeorm-linq-repository#12]
I have this query done using query builder:

```ts
    public findByIdAndOwner(id: number, owner: User): Promise<Song|undefined> {
        return this.createQueryBuilder("song")
            .where("song.id = :id", { id })
            .innerJoin("song.owner", "owner", "owner.id = :ownerId")
            .addParameters({ ownerId: owner.id })
            .getOne();
    }
```
I want to return the entity by id if owner from parameters is an owner in database (relation song => User) or `undefined` if not (not found due to innerJoin).

```ts
@Entity()
export class Song {

    @PrimaryGeneratedColumn()
    public readonly id: number;

    @ManyToOne(_type => User, { nullable: false })
    public owner: User;

}
```

I've tried `includeWhere` but it's not working - just don't include, returns entity without owner:
```ts
    public findByIdAndOwner(id: number, owner: User): Promise<Song|undefined> {
        return this.getOne()
            .where(song => song.id).equal(id)
            .includeWhere(song => song.owner, owner => owner.id).equal(owner.id)
            .toPromise();
    }
```
How can I achieve this kind of behaviour in the linq style?

**Comment by IRCraziestTaxi** [comment]
@19majkel94 I just found an issue similar to this this morning... can you tell me what happens if you replace .innerJoin in the QueryBuilder query with .leftJoin or .leftJoinAndSelect? (I'm away from my PC for a while.) That query with .leftJoinAndSelect instead of .innerJoin is essentially what should be happening behind the scenes. I will need to find out where the issue lies, whether it be using the wrong join function or another bug somewhere. I will investigate for myself after work, but I can get a head start on it if you can provide me with the results of replacing .innerJoin with .leftJoin and .leftJoinAndSelect.

As a side note, I actually find it interesting that .innerJoin rather than .innerJoinAndSelect returns the owner with the song. I thought that was the point of *AndSelect.

**Comment by 19majkel94** [comment]
> can you tell me what happens if you replace .innerJoin in the QueryBuilder query with .leftJoin or .leftJoinAndSelect?

This is the case what I'm talking about right now. My old query is doing innerJoin, so:
- property `owner` is not showing in entity (no data leak, I can return the entity from my REST API)
- if entity owner id is not equal the user id from token, the whole entity is undefined

And your linq-style queries with `includeWhere` just loads or not the relation as it build query with `leftJoinAndSelect`. It's ok, it's not a bug, but I need something more :wink:

Take a look what's the difference between left and inner join:
![](https://i.stack.imgur.com/VQ5XP.png)

So when I do inner join with `where` constraint, it select the entity with joined relation when the owner.id match or null/empty when the id is not matching (user is not an owner of an entity).

I want to recreate this behavior which I've done with query builder and `.innerJoin`.

`includeWhere` of course work like `xxxAndSelect`. But the problem is that `includeWhere` create a left join statement so it will join the relation if the condition is fulfilled, otherwise the property (like song.owner) will be undefined. I need the inner join feature that will result the whole entity will be undefined when the selected relation condition is not fulfilled.

I would like to see overloaded `.where` (+ and, or) which can take lambdas just like `includeWhere`, but with no include no `xxxAndSelect`:
```ts
public findByIdAndOwner(id: number, owner: User): Promise<Song|undefined> {
        return this.getOne()
            .where(song => song.id).equal(id)
            .andWhere(song => song.owner, owner => owner.id).equal(owner.id)
            .toPromise();
    }
```

**Comment by IRCraziestTaxi** [comment]
Oh! I see what you want now. I misunderstood before.

That is a great point; inner joins are important. I will work on it.

**Comment by IRCraziestTaxi** [comment]
Fixed in v0.1.0!

**Comment by IRCraziestTaxi** [comment]
Or, rather, 0.1.1. Had to make an update due to a dependency needing to be updated as well.

**Comment by IRCraziestTaxi** [comment]
@19majkel94 Thank you VERY much for the overload suggestion. It worked like a charm!
