### ISSUE TITLE
ts-simple-nameof as a devDeps instead of normal dependency

### ISSUE THREAD

**Issue by 19majkel94** [IRCraziestTaxi/typeorm-linq-repository#17]
You use `ts-simple-nameof` as a normal dependency in the code:
```ts
import { nameof } from "ts-simple-nameof";
```
So now with the newest version I have runtime error `cannot find module ...` - I have to install it manually like a peerDependency.

Every lib that you import in code should be listed in `dependencies` section of package.json. `devDependencies` is for tools like linters, test runners or build tools (even typescript).

**Comment by 19majkel94** [comment]
To be precise - `ts-simple-nameof` should be in `dependencies` section and `typeorm` should be in `peerDependencies` 😉

**Comment by IRCraziestTaxi** [comment]
Fixed in v0.1.2.
