### ISSUE TITLE
Integration with inversifyjs

### ISSUE THREAD

**Issue by dan1er** [IRCraziestTaxi/typeorm-linq-repository#26]
Hey man, amazing work!
I'm trying to integrate with inversify, I followed your indications,
I decorated the RepositoryBase class this way:

```javascript
import { decorate, injectable, unmanaged } from "inversify";
import { RepositoryBase } from "typeorm-linq-repository";

decorate(injectable(), RepositoryBase);
decorate(unmanaged(), RepositoryBase, 0);

export { RepositoryBase }
```

and then
```javascript
import {IRepositoryBase} from "typeorm-linq-repository";
import {IUser, User} from "../entity/user";
import {injectable} from "inversify";
import {RepositoryBase} from "./base.repository";

export interface IUserRepository extends IRepositoryBase<IUser> {
}

@injectable()
export class UserRepository extends RepositoryBase<IUser> implements IUserRepository {
    public constructor() {
        super(User);
    }
}

```

but I'm having this error `TypeError: Class constructor RepositoryBase cannot be invoked without 'new'`,

Any ideas of what I might be doing wrong?

**Comment by IRCraziestTaxi** [comment]
Thank you, and thanks for using the project!

Hmm... everything looks good at first sight. How are you injecting your repository into the class that is using it?

Obviously, your project may differ greatly, but here is a bottom-up example of how I use inversify:

`UserBL.ts`
```ts
// import blah blah blah...

@injectable()
export class UserBL implements IUserBL {
    private readonly _userRepository: IUserRepository;

    // UserBL is obtained from IocContainer (see examples below),
    // then UserRepository is automatically injected into UserBL's constructor.
    public constructor(userRepository: UserRepository) {
        this._userRepository = userRepository;
    }

    // Methods and such.
}
```

`inversifyconfig.ts`
```ts
import { Container } from "inversify";
// import blah blah blah...

const IocContainer: Container = new Container();

IocContainer.bind<UserRepository>(UserRepository).toSelf();
IocContainer.bind<UserBL>(UserBL).toSelf();

export { IocContainer };
```

`UserController.ts`
```ts
// import blah blah blah...

// Going to use routing-controllers decorators because that's what I'm used to,
// but the main point is getting UserBL from the IocContainer in the controller's constructor;
// this is required in order to initiate the chain of dependency injection.

@JsonController("/users")
export class UserController {
    private readonly _userBL: UserBL;

    public constructor() {
        // IocContainer was imported from inversifyconfig.ts (or whatever you chose to name it).
        // IocContainer.get initiates the chain of dependency injection;
        // when UserBL is obtained from IocContainer, UserRepository is automatically injected into its constructor.
        this._userBL = IocContainer.get<UserBL>(UserBL);
    }
}
```

Hopefully that is all you're missing; if not, then I'll have to look into it further, but what you've provided looks fine, so I suspect something along the lines of the code above is what you're missing.

**Comment by dan1er** [comment]
@IRCraziestTaxi  Thanks for your quick response,
I replicated your code above, and I'm still having the same issue, the only difference I have is that I am using inversify-express-utils instead of typeorm-routing-controllers-extensions, but I don't think is related

**Comment by IRCraziestTaxi** [comment]
@dan1er Yeah, that definitely should not be related. Could you please share your code for setting up your inversify Container and getting your classes from it?

**Comment by dan1er** [comment]
@IRCraziestTaxi Yes, you can see it in this repository https://github.com/dan1er/typeorm-linq-test

**Comment by IRCraziestTaxi** [comment]
@dan1er Thanks. I will check out the code and look into it a little bit later, but I do notice one thing: your tsconfig needs to target es6 to use typeorm and typeorm-linq-repository. Let me know if changing that works.

**Comment by dan1er** [comment]
@IRCraziestTaxi That fixed it! I don't know how I didn't see it! Thanks a lot, you saved my day

**Comment by IRCraziestTaxi** [comment]
@dan1er No problem! :) Thanks again for using typeorm-linq-repository and enjoy!
