### ISSUE TITLE
Dependabot for keeping NPM dependencies up to date

### ISSUE THREAD

**Issue by mattwelke** [IRCraziestTaxi/typeorm-linq-repository#45]
I noticed in this PR (https://github.com/IRCraziestTaxi/typeorm-linq-repository/pull/44) that the TypeORM dependency had fallen a bit out of date. I just wanted to let you know that I use Dependabot with GitHub for my open source repos (it's free for public repos) to automatically have PRs opened for me when a dependency is out of date. I can even set it to automatically merge the PR and if I configure CI/CD, I can have a deploy or publish step occur automatically too. I think it would be useful for a library like this so that people using both TypeORM and this LINQ addon won't have to worry about the TypeORM dependency here getting out of date.

https://dependabot.com/

**Comment by IRCraziestTaxi** [comment]
Happy to report I finally got around to setting up dependabot with my repos. Thanks for the suggestion! :)

**Comment by IRCraziestTaxi** [comment]
@mattwelke Any chance you have a repo of yours that you can recommend to look at for a simple introduction to GitHub's CI with a node project? I looked at a few pages about their "Actions" but a hands on example would help me a lot.

Thanks!

**Comment by mattwelke** [comment]
I actually converted a few of my repos from CircleCI to GitHub Actions for the CI so that dependant would auto merge the PRs. Look at my "postgres-typeorm-example". Think I did that one.
