### ISSUE TITLE
Logical Operators lessThan, greaterThan etc don't work with dates

### ISSUE THREAD

**Issue by irissoftworks** [IRCraziestTaxi/typeorm-linq-repository#46]
A few places in the docs mention using lessThan, greaterThan with a variable named date 
`    .and(u => u.lastLogin)
    .greaterThan(date);`

Currently the typings don't allow for passing in dates, and it doesn't seem to work, even with a cast to any:
`    greaterThan(value: number): IQuery<T, R, P>;`

Any ideas on this ?

**Comment by IRCraziestTaxi** [comment]
This was a pretty severe oversight on my part. I will look into this and publish a fix asap.

Thanks for using typeorm-linq-repository! I'm glad it's still seeing some use and generating some issues so that it can continue to be improved.

**Comment by irissoftworks** [comment]
This library is brilliant, a joy to work with, and it definitely deserves a lot more love from the community. 

In my opinion, for pretty much all cruddy stuff, such as including / joining relations etc this stuff beats typeorm native repos hands down. 

I basically don't have anything but linq-repositories now in the microservices that use typeorm and some of them do pretty complex stuff. You can write advanced stuff with it, and fall back to the query builder for the cases where it needs works perfect. 

I actually found a few pieces that need fixing, this one was the biggest blocker, but there's a couple other issues I have seen! Would love to help fixing, but it has been super hard with the time constraints. 

I got another small one to raise, will try to raise it later on today !

**Comment by IRCraziestTaxi** [comment]
Fixed in `1.0.0-alpha.14`!
