### ISSUE TITLE
Support for lazy relations

### ISSUE THREAD

**Issue by ikatun** [IRCraziestTaxi/typeorm-linq-repository#48]
Awesome library :)

But is there a support for lazy relations?

Lazy relations supported by typeorm have a Promise<> type which appears to mess up typings for typeorm-linq-repository for include and includeThen calls.

If I ignore type errors, the code runs fine, but type errors prevent the usage of autocomplete when writing queries.

**Comment by IRCraziestTaxi** [comment]
Fixed in `1.0.0-alpha.14`!
