### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by irissoftworks** [IRCraziestTaxi/typeorm-linq-repository#54]
Again thanks for the great library!

One thing that is causing pain at the moment is that I am not sure how to handle transactions or if they are supported and I am currently falling back to using the typeorm native repos or the native entity manager to handle transactions. 

I could be missing something but if not is there currently a plan to add support for transactions ? 

There is an implementation of a powerful `@Transaction` decorator here https://github.com/typeorm/typeorm/issues/1895 

This looks not too hard to expose a hook from linq-repos so that a third party package can provide the entity manager to be used ? In any case, this would be really helpful for my project so I am willing to help with anything needed!

**Comment by IRCraziestTaxi** [comment]
Thanks for bringing this up! I have thought about this a lot and would like to finally get around to implementing it. I will look at the `@Transaction` decorator - hopefully it will help to take care of this issue quickly.

**Comment by irissoftworks** [comment]
Awesome man, cheers for the prompt reply. 

On a sidenote, to save you some time in digging, that approach requires middleware to be in place to run the requests inside the CLS context, which is probably not relevant to typeorm-linq-repos. 

I think the whole thing may require some thought as to how it could be integrated, which and how many packages have to be created. I am assuming you would want to couple linq-repositories decorators to web frameworks like express or hapi etc ?

```
public constructor(entityType: EntityConstructor<T>, options?: RepositoryOptions) {
        let autoGenerateId: boolean = true;
        let connectionName: string;

        if (options) {
            if (typeof (options.autoGenerateId) === "boolean") {
                autoGenerateId = options.autoGenerateId;
            }
            if (options.connectionName) {
                connectionName = options.connectionName;
            }
        }

        this._repository = getConnectionManager()
            .get(connectionName)
            .getRepository<T>(entityType);
        this._autoGenerateId = autoGenerateId;
    }
```

Maybe allow overriding the way the LinqRepository class gets the entity manager via a factory would be an option ? This would remove a lot of work from what you would have to do and solve the problem ?

Also, the concept of a transaction decorator using the CLS can be really powerful, but that implementation is a bit too naive to ship as a package I would say, I'm thinking about creating a more resilient one.

**Comment by IRCraziestTaxi** [comment]
Ah, ok, I was kinda speed reading the original comment and misunderstood. I saw `@Transaction` and assumed it was an actual decorator in TypeORM. My bad!

You are correct - I will not create any unnecessary coupling to another framework. This lib is only intended to wrap TypeORM; therefore, TypeORM will remain its only peer dependency if I can help it.

The factory option approach sounds promising. I will also dig into that issue you linked regarding the `@Transaction` implementation and try to get some ideas from it.

Thanks a bunch! I really appreciate the feedback and ideas.

**Comment by IRCraziestTaxi** [comment]
Using the changes made to `typeorm-transactional-cls-hooked` per https://github.com/typeorm/typeorm/issues/3884, `typeorm-transactional-cls-hooked` is now VERY easy to use with `typeorm-linq-repository`. Simply call `patchTypeORMRepositoryWithBaseRepository();` when bootstrapping your app and you are good to go!

Although I am disappointed in myself for not supporting transactions sooner, I believe using this approach is far cleaner than making `typeorm-transactional-cls-hooked` a dependency, peer or otherwise, of `typeorm-linq-repository`. I have updated the README accordingly and will close this issue for now.
