### ISSUE TITLE
set setTypeParser to manage UTC datetime

### ISSUE THREAD

**Issue by freefred81** [IRCraziestTaxi/typeorm-linq-repository#78]
Hi .. 

quick question ...

i have some problems with utc date manage (as many other has on postgres)

i have found a solution here 

[(https://github.com/typeorm/typeorm/issues/3286)]

so i try something like: 

```
 let driver = this._accountRepository.typeormRepository.manager.connection.driver as any;
 driver.postgres.defaults.parseInputDatesAsUTC = false;
 driver.postgres.types.setTypeParser(1114, (str: any) => str);
```
or also (i use a nest.js app)

```
export const AccountRepositoryProvider = {
  provide: 'AccountRepository',
  useFactory: ((connection: Connection) => {
    let driver = connection.driver as any;
    driver.postgres.defaults.parseInputDatesAsUTC = false;
    driver.postgres.types.setTypeParser(1114, (str: any) => str);
   return connection.getCustomRepository(AccountRepository)
  }),
  inject: [Connection],
};
```
which be more clean (so i don't have to repeat the snippet every where..

but it looks not doing nothing ..

i have also try (just to check) if i put a 

 `driver.postgres.types.setTypeParser(1114, (str: any) => new Date());`

but nothing happen

Thnx!!

**Comment by IRCraziestTaxi** [comment]
It looks like this has nothing to do with typeorm-linq-repository but rather with setup in TypeORM and Nest. I'm going to go ahead and close this for that reason. I would suggest opening an issue with either [Nest](https://github.com/nestjs/nest) or, more likely, their [TypeORM module](https://github.com/nestjs/typeorm). I would see what I can do to help out but honestly I have no experience with Nest and won't have time any time soon to dabble in it. :/
