### ISSUE TITLE
ANY PLAN FOR MONGODB SUPPORT?

### ISSUE THREAD

**Issue by freefred81** [IRCraziestTaxi/typeorm-linq-repository#80]
Hi Do you have any plan to support also MongoDB?

maybe also for basic query (where , project etc)

Thnx!

**Comment by IRCraziestTaxi** [comment]
Hey @freefred81,

Honestly, I never use Mongo, but I took for granted that TypeORM's QueryBuilder (which at the end of the day is what this lib uses to generate the queries) already translated the SQL-like queries generated by QueryBuilder into Mongo queries. Is that not the case?

I don't have a ton of time to dig into it at the moment, but if you can give me an example of how a QueryBuilder call for Mongo differs from one for SQL, I'll look into it when I get some time.

Thanks!

**Comment by freefred81** [comment]
Hi... You're nice as usual .. really thnx for your time!..you have to give a try to mongoDb!!!.. i really love it (really really better than SQL db)..

these are some example of common where clause on mongodb TypeORM repo:


```
// SAME AS your GetONE()
const isOnDb = await this.callRepository.findOne({
                fromNumber: call.fromNumber,
                insertDatetime: new Date(+call.date).toISOString(),
                number: call.number      
            });

// same as GetAll()
const allOnDbs = await this.callRepository.find({
                fromNumber: call.fromNumber,
                insertDatetime: new Date(+call.date).toISOString(),
                number: call.number      
            });

```

**Comment by IRCraziestTaxi** [comment]
Hey @freefred81,

I finally got a few minutes to look into it a little more and I found that TypeORM handles mongo queries in a different way entirely than it does for SQL queries. It appears that mongo queryies don't even use TypeORM's `QueryBuilder`, which is evidently only for SQL queries and is what this lib wraps.

You can get some context via the discussion [in this TypeORM issue about it](https://github.com/typeorm/typeorm/issues/148).

In fact, it seems that mongo queries are so straightforward that a `QueryBuilder` doesn't really make sense for it.

Therefore, I would say that this lib will not in the foreseeable future support mongo queries as it was built entirely around SQL querying. If anything, mongo query support would need to be implemented in a new lib altogether. I cannot fathom what the time frame for that would be but it would not be any time soon, unfortunately.

However, if you so choose, you could use this lib's `LinqRepository` for the ease of creating a repository and using the create/update/delete methods and perform your queries by using `LinqRepository`'s `typeormRepository` property to call its `find` and `findOne` methods, but that may be overkill.

I will keep this issue open while I decide what should be done about it (new lib, etc.).

**Comment by IRCraziestTaxi** [comment]
Hey @freefred81, sorry for the long period of inactivity on this.

Given the thoughts above, I do not feel like modifying this library to support TypeORM's Mongo functions would be a good move. This library was build exclusively with SQL queries in mind, so I would not feel right adding complexity to support a completely different database engine, especially given that TypeORM's query builder for Mongo is totally different from its SQL query builder.

I can't promise that I'll be able to find time in the future to create a similar library to handle Mongo queries given my lack of free time these days in general as well as the fact that I never use Mongo anymore, just SQL and occasionally dynamo.

I'm going to go ahead and close this one.
