### ISSUE TITLE
Subquery Support

### ISSUE THREAD

**Issue by ivanjd** [IRCraziestTaxi/typeorm-linq-repository#86]
Does the lib support subqueries. Imagine `Products` that have `Orders`, while `Orders` have `Shipments`. How would I query for all products and join them with only those orders that have a shipment in a pending state using the typeorm-linq-repository api.

**Comment by IRCraziestTaxi** [comment]
Hmm... yes, the lib does support subqueries (or "inner queries" as I called them in the readme) via the `inSelected` and `notInSelected`methods.

However, for the query you have described, I would suspect it would be as simple as:

```ts
const products = await productRepository
    .getAll()
    // joinAlso performs a left join.
    .joinAlso(p => p.orders)
    // join performs an inner join.
    .join(o => o.shipments)
    // This join condition on our inner join
    // filters the Orders we get back by the Order's Shipment status,
    // but since we performed a left join on Orders, no Products will be filtered.
    .where(s => s.state)
    // Assuming this is an enum and, per the last few comments in #85,
    // must (for now at least) use { matchCase: true } when comparing a string enum.
    .equal(ShipmentState.Pending, { matchCase: true });
```

Let me know if that makes sense. I will leave the issue open for now but I assume that should address your question.

**Comment by IRCraziestTaxi** [comment]
Another note: if you want to actually include the `Order` and `Shipment` objects in your `Product` results, you can use `join` functions after `include` functions on the same relationship to filter what is included.

i.e., if you wanted to get all Products and also include the Products' Orders, but only where the Order's Shipment state is pending, you would use:

```ts
const products = await productRepository
    .getAll()
    // Include the Orders objects on the returned Products.
    .include(p => p.orders)
    // Also include the Order's Shipment;
    // we will filter the included Orders with the join function below.
    .thenInclude(o => o.shipments)
    // joinAlso performs a left join.
    // Note that joinAlso (left join) does not undo the include above.
    .joinAlso(p => p.orders)
    // join performs an inner join.
    // Note that join (inner join) will add conditions to the thenInclude above
    // to filter included Orders.
    .join(o => o.shipments)
    // This join condition on our inner join
    // filters the Orders we get back by the Order's Shipment status,
    // but since we performed a left join on Orders, no Products will be filtered.
    .where(s => s.state)
    // Assuming this is an enum and, per the last few comments in #85,
    // must (for now at least) use { matchCase: true } when comparing a string enum.
    .equal(ShipmentState.Pending, { matchCase: true });
```

**Comment by ivanjd** [comment]
I have used `include` and `join` to get back the joined entity, this is not a problem. However, I don't think the query you propose will solve my problem. Basically what I need is: 
`Products LEFT JOIN (Orders INNER JOIN Shipments)`
Imagine a case where there are no Shipments at all. Then:
`Products LEFT JOIN Orders INNER JOIN Shipments`
will result in an empty result set, but I want the products always included regardless of the existence or inexistence of shipments.

**Comment by IRCraziestTaxi** [comment]
Sorry it took me a while to reply to this.

I'm not really sure what you mean... `Products LEFT JOIN ...` will result in the `Product`s being included regardless of whether the `Product`'s `Order` is since it is a `LEFT JOIN`.

Note in my example that `joinAlso` is used to perform a `LEFT JOIN`, not `join`, which does produce an `INNER JOIN`.

Let me know if I am still misunderstanding something.

**Comment by IRCraziestTaxi** [comment]
Hey @ivanjd, sorry for the period of inactivity on my part. I assume my response was able to shed some light on the situation. If not, feel free to reopen, hopefully with a small repro I can clone and look at.
